apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  selector:
    app: hello-world
    env: prod
    version: latest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
