apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: hello-world
    version: latest
    env: prod
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 3000
    targetPort: 3000